# Generated by Django 2.0.7 on 2020-09-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('current_cases', models.IntegerField(default=0)),
                ('predicted_cases', models.IntegerField(default=0)),
            ],
        ),
    ]
