# Generated by Django 2.1.7 on 2020-09-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='population',
            field=models.IntegerField(default=0),
        ),
    ]
